'use strict';
const { _electron:electron }=require('playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const {unpack}=require('../src/backup');
const root=path.resolve(__dirname,'../..'),output=path.join(root,'.test-output');
fs.mkdirSync(output,{recursive:true});
const profile=fs.mkdtempSync(path.join(output,'profile-'));
let application;
(async()=>{
  const executablePath=process.env.AGNIA_TEST_EXE||require('electron');
  application=await electron.launch({executablePath,args:[...(process.env.AGNIA_TEST_EXE?[]:[path.resolve(__dirname,'..')]),'--test-profile='+profile],timeout:30000,
    env:{...process.env,ELECTRON_ENABLE_LOGGING:'1'}});
  const window=await application.firstWindow();const errors=[];window.on('pageerror',e=>errors.push(e.message));
  await window.waitForFunction(()=>document.querySelector('#empty')&&!document.querySelector('#empty').hidden);
  await window.locator('#new-name').fill('demo_main');await window.locator('#add-form button').click();
  await window.locator('#account-title').filter({hasText:'demo_main'}).waitFor();
  await window.locator('[data-page=games]').click();
  const ids=Array.from({length:65},(_,i)=>i+1);
  await window.locator('#appids').fill(ids.join(', '));await window.locator('#auto-start').check();await window.locator('#save').click();
  await window.waitForFunction(()=>document.querySelector('#dirty').textContent==='Сохранено');
  await window.locator('[data-page=presets]').click();await window.locator('#preset-name').fill('Очередь на ночь · 65 игр');await window.locator('#preset-save').click();
  await window.getByText('Очередь на ночь · 65 игр',{exact:true}).waitFor();
  await window.locator('[data-page=games]').click();await window.locator('#add-popular').click();
  await window.getByText('Популярные игры добавлены в локальную библиотеку',{exact:true}).waitFor();
  await window.locator('#search').fill('Dota');await window.locator('#select-all').click();await window.locator('#save').click();
  await window.waitForFunction(()=>document.querySelector('#dirty').textContent==='Сохранено');
  await window.locator('#search').fill('');
  await window.locator('[data-page=stats]').click();await window.locator('#goal-appid').fill('570');await window.locator('#goal-hours').fill('100');await window.locator('#goal-save').click();
  await window.getByText('Цель сохранена',{exact:true}).waitFor();
  await window.locator('[data-page=settings]').click();await window.locator('#startup-delay').fill('90');await window.locator('#schedule-enabled').check();
  await window.locator('#schedule-start').fill('22:00');await window.locator('#schedule-end').fill('06:00');await window.locator('#options-form button').click();
  await window.getByText('Автоматизация сохранена',{exact:true}).waitFor();
  const backup=path.join(output,'ui-backup.agnia');
  await application.evaluate(({dialog},file)=>{dialog.showSaveDialog=async()=>({canceled:false,filePath:file});},backup);
  await window.locator('#backup-password').fill('test archive password');await window.locator('#backup-export').click();await window.getByText('Резервная копия сохранена',{exact:true}).waitFor();
  const data=unpack(fs.readFileSync(backup),'test archive password');assert.equal(data.config.accounts[0].appids.length,66);assert.equal(data.features.options.startupDelay,90);
  assert.equal(data.features.accounts[data.config.accounts[0].id].presets[0].appids.length,65);
  // The UI must preserve unsaved edits through the one-second snapshot refresh.
  await window.locator('[data-page=games]').click();await window.locator('#appids').fill('440, 570, 730');
  await window.waitForTimeout(1300);assert.equal(await window.locator('#appids').inputValue(),'440, 570, 730');await window.locator('#save').click();
  await window.getByText('Настройки игр сохранены',{exact:true}).waitFor();
  await window.locator('#new-name').fill('demo_second');await window.locator('#add-form button').click();
  await window.locator('#account-title').filter({hasText:'demo_second'}).waitFor();
  await window.locator('[data-page=presets]').click();assert.equal(await window.getByText('Очередь на ночь · 65 игр',{exact:true}).count(),0);
  await window.locator('#accounts button').filter({hasText:'demo_main'}).click();
  await window.getByText('Очередь на ночь · 65 игр',{exact:true}).waitFor();
  for(const name of ['boost','games','presets','stats','diagnostics','telegram','settings']){
    await window.locator(`[data-page=${name}]`).click();await window.waitForTimeout(180);
    assert.equal(await window.locator('.page:visible').count(),1,name+' page visibility');
    const overflow=await window.evaluate(()=>document.documentElement.scrollWidth>innerWidth);assert.equal(overflow,false,name+' horizontal overflow');
    await window.screenshot({path:path.join(output,name+'.png'),fullPage:true});
  }
  await application.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].setSize(980,700));
  await window.locator('[data-page=games]').click();await window.waitForTimeout(200);
  assert.equal(await window.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'small window overflow');
  await window.screenshot({path:path.join(output,'games-small.png'),fullPage:true});
  await window.locator('[data-page=boost]').click();await window.locator('#password').fill('smoke-password');await window.locator('#start').click();
  await window.locator('#notice').filter({hasText:'Steam отключён в тестовом профиле'}).waitFor();
  assert.deepEqual(errors,[]);const result={ok:true,profile,checks:['seven sections','65-game preset','multi-account isolation','popular/name selection','goal','automation','encrypted backup UI','unsaved edit preservation','980px layout','offline test isolation'],pageErrors:errors};
  fs.writeFileSync(path.join(output,'ui-smoke.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result));
})().catch(e=>{console.error(e);process.exitCode=1;}).finally(async()=>{if(application)await application.close();});
